# ==========================================
# 共用 API 設定
# ==========================================
# Token 與 Base URL 一律從環境變數讀取，不在本檔寫死明文密鑰。
# 請在 shell profile（例如 ~/.bashrc）設定：
#   export CLIPROXYAPI_AUTH_TOKEN="你的 token"
#   export CLIPROXYAPI_BASE_URL="http://127.0.0.1:8317"   # 可選，未設定則自動推導 WSL host IP
#
#CLIPROXYAPI_BASE_URL="http://127.0.0.1:8317"
# 若未明確設定 BASE_URL，自動以 WSL nameserver IP 推導 Windows host 位址。
if [ -z "${CLIPROXYAPI_BASE_URL:-}" ]; then
  WIN_HOST_IP=$(awk '/nameserver/ {print $2}' /etc/resolv.conf)
  CLIPROXYAPI_BASE_URL="http://${WIN_HOST_IP}:8317"
fi
# 確保 token 已設定；未設定時提示如何設定，避免 alias 帶空 token 呼叫。
if [ -z "${CLIPROXYAPI_AUTH_TOKEN:-}" ]; then
  echo "cli.sh：尚未設定 CLIPROXYAPI_AUTH_TOKEN，請先執行 export CLIPROXYAPI_AUTH_TOKEN=\"<你的 token>\"" >&2
fi
# 以 gpt-5.6-sol (370K context) 為主線，旁支用 gpt-5.6-luna (370K context) 跑子代理！
# 注意: gpt-5.6 在 Codex 最大只有 371K Context Window，但是 OpenAI API 則有完整的 1M Tokens
alias claudex='\
    ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
    ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
    ANTHROPIC_DEFAULT_HAIKU_MODEL=gpt-5.3-codex \
    ANTHROPIC_DEFAULT_SONNET_MODEL=gpt-5.6-luna \
    ANTHROPIC_DEFAULT_OPUS_MODEL=gpt-5.6-sol \
    ANTHROPIC_DEFAULT_FABLE_MODEL=gpt-5.6-sol \
    CLAUDE_CODE_DISABLE_1M_CONTEXT=1 \
    CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=80 \
    CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-luna \
    CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
    CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
    CLAUDE_CODE_MAX_CONTEXT_TOKENS=371000 \
    CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
    ENABLE_TOOL_SEARCH=false \
    claude --model gpt-5.6-sol'

# 以 glm-5.2 為主線(1M context)，旁支用 gpt-5.6-luna (370K context) 跑子代理！
# 注意: gpt-5.6 在 Codex 最大只有 371K Context Window，但是 OpenAI API 則有完整的 1M Tokens
#CLAUDE_CODE_DISABLE_1M_CONTEXT=1 \
#CLAUDE_CODE_AUTO_COMPACT_WINDOW=200000 \
alias claudex-glm='\
    ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
    ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
    ANTHROPIC_DEFAULT_HAIKU_MODEL=gpt-5.3-codex \
    ANTHROPIC_DEFAULT_SONNET_MODEL=gpt-5.6-luna \
    ANTHROPIC_DEFAULT_OPUS_MODEL=gpt-5.6-sol \
    ANTHROPIC_DEFAULT_FABLE_MODEL=gpt-5.6-sol \
    CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=80 \
    CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-luna \
    CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
    CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
    CLAUDE_CODE_MAX_CONTEXT_TOKENS=1050000 \
	CLAUDE_CODE_AUTO_COMPACT_WINDOW=1050000 \
    CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
    ENABLE_TOOL_SEARCH=false \
	CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT=1 \
    claude --model glm-5.2'

# 以 gpt-5.6-sol 為主線，旁支用 gpt-5.3-codex-spark 跑子代理！
# 注意: gpt-5.6 在 Codex 最大只有 371K Context Window，但是 OpenAI API 則有完整的 1M Tokens
alias claudex3='\
    ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
    ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
    ANTHROPIC_DEFAULT_HAIKU_MODEL=gpt-5.3-codex \
    ANTHROPIC_DEFAULT_SONNET_MODEL=gpt-5.6-luna \
    ANTHROPIC_DEFAULT_OPUS_MODEL=gpt-5.6-sol \
    ANTHROPIC_DEFAULT_FABLE_MODEL=gpt-5.6-sol \
    CLAUDE_CODE_DISABLE_1M_CONTEXT=1 \
    CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=80 \
    CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.3-codex-spark \
    CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
    CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
    CLAUDE_CODE_MAX_CONTEXT_TOKENS=371000 \
    CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
    ENABLE_TOOL_SEARCH=false \
    claude --model gpt-5.6-sol'

# ==========================================
# OpenAI 系列
# ==========================================
alias cx-sol="CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-sol \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=371000 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gpt-5.6-sol"

alias cx-terra="CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-terra \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=371000 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gpt-5.6-terra"

alias cx-luna="CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.6-luna \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=371000 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=128000 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gpt-5.6-luna"

alias cx-codex="CLAUDE_CODE_SUBAGENT_MODEL=gpt-5.3-codex \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=128000 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=32000 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gpt-5.3-codex"

# ==========================================
# xAI 系列
# ==========================================
alias cx-grok="CLAUDE_CODE_SUBAGENT_MODEL=grok-4.5 \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=128000 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=32000 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model grok-4.5"

# ==========================================
# Google 系列
# ==========================================
alias cx-gemini-pro="CLAUDE_CODE_SUBAGENT_MODEL=gemini-3.1-pro \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=2097152 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=8192 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gemini-3.1-pro"

alias cx-gemini-flash="CLAUDE_CODE_SUBAGENT_MODEL=gemini-3.5-flash \
CLAUDE_CODE_ALWAYS_ENABLE_EFFORT=1 \
CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY=3 \
CLAUDE_CODE_MAX_CONTEXT_TOKENS=1048576 \
CLAUDE_CODE_MAX_OUTPUT_TOKENS=65536 \
DISABLE_AUTO_COMPACT=1 \
ENABLE_TOOL_SEARCH=false \
ANTHROPIC_BASE_URL=$CLIPROXYAPI_BASE_URL \
ANTHROPIC_AUTH_TOKEN=$CLIPROXYAPI_AUTH_TOKEN \
claude --model gemini-3.5-flash"
